name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

  publish:
    name: Publish to Maven Central
    if: "github.event.release || github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup credentials
        run: |
          echo $GPG_KEY_FILE | base64 --decode > secring.gpg
          echo $GRADLE_PROPERTIES_FILE | base64 --decode > gradle.properties
          echo 'Setup credentials successfuly!'

      - name: Publish package
        run: ./gradlew publishReleasePublicationToSonatypeRepository
